### ISSUE TITLE
Support using advanced notation in the YAML for an import

### ISSUE THREAD

**Issue by astaruch** [astaruch/garmin-workouts-cli#14]
Currently I can enter only `hr_low`, `hr_high`.

Support the:
```
hr: 150-170
hr: 150 - 170
```

or instead `distance: 5000`, be able to enter
```yaml
distance: 5000m
distance: 5km
distance: 5 km 
distance: 5000 m
```
