### ISSUE TITLE
Support using variables in the YAML for an import

### ISSUE THREAD

**Issue by astaruch** [astaruch/garmin-workouts-cli#15]
Check whether I can implement just YAML Anchors, or I need to use Jinja.

Intention:
```yaml

LT_PACE: 150-170
EASY_PACE: 130-170

workouts:
  - name: monday
     steps:
         - type: run
           distance: 10 km
           hr: {{ EASY_PACE }}  // option 2
           hr: *EASY_PACE // option 1
```
