### ISSUE TITLE
Add sorting of keys for output YAML

### ISSUE THREAD

**Issue by astaruch** [astaruch/garmin-workouts-cli#17]
Now when a user import a workout like this:
```yaml
name: 'W17 - LT 6/13km'
id: 414605489
steps:
  - type: warmup
    distance: 4000
    hr_low: 137
    hr_high: 156
  - type: run
    distance: 6000
    hr_low: 157
    hr_high: 174
  - type: cooldown
    distance: 3000
    hr_low: 137
    hr_high: 156
```

It will be stored back as:
```yaml
id: 414870637
name: W17 - LT 6/13km
steps:
- distance: 4000
  hr_high: 156
  hr_low: 137
  type: warmup
- distance: 6000
  hr_high: 174
  hr_low: 157
  type: run
- distance: 3000
  hr_high: 156
  hr_low: 137
  type: cooldown
```
When they are sorted, or like:
```yaml
name: W17 - LT 6/13km
steps:
- type: warmup
  distance: 4000
  hr_low: 137
  hr_high: 156
- type: run
  distance: 6000
  hr_low: 157
  hr_high: 174
- type: cooldown
  distance: 3000
  hr_low: 137
  hr_high: 156
id: 414882467
```
when they are used as from Python object (order is like it was parsed).

Add a new mechanism, that exporting/dumping the object will be in a specific order.
