### ISSUE TITLE
Export one run workout to custom yaml format

### ISSUE THREAD

**Issue by astaruch** [astaruch/garmin-workouts-cli#8]
As a user I want to be able run the `garmin-workouts-cli` and export a run workout into the readable yaml format.

Keep it easy from the start:
- take the first run workout that is found - it will be the JSON
- take this JSON, and export to YAML format
- display only the relevant information, that will lead to later recontruction
- store it either on disk or on stdout

Draft how it could look like - https://connect.garmin.com/modern/workout/edit/280384519?from=summary:
```yaml
run:
  name: Week 1 - Long 21K MP+19 (4:56)
  steps:
    - type: repetition
      count: 21
      steps:
        - type: run
          distance: 1000
          pace_low: 4:54 min/km
          pace_high: 4:58 min/km
    - type: run
      lap_button: yes
    - type: repetition
      count: 2
      steps:
        - type: run
          distance: 1000
        - type: recovery
          lap_button: yes
```

Throw an exception with nice user error if a field, which is not yet parsable, will be found.

Thanks to this we can build a resilient system, and then use this for all workouts and reverse engineer it.
